# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classCode', models.CharField(max_length=10)),
                ('className', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('cohort', models.IntegerField()),
                ('current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='gsClassStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodstanding.gsClass')),
            ],
        ),
        migrations.CreateModel(
            name='gsClassStudentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('note', models.TextField()),
                ('classStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodstanding.gsClassStudent')),
            ],
        ),
        migrations.CreateModel(
            name='gsStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('cohort', models.IntegerField()),
                ('current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='gsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('current', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='gsclassstudent',
            name='gsStudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodstanding.gsStudent'),
        ),
        migrations.AddField(
            model_name='gsclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodstanding.gsUser'),
        ),
    ]
